//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkolaProjektniCentar
{
    using System;
    using System.Collections.Generic;
    
    public partial class KontaktTelefon
    {
        public long IdTelefona { get; set; }
        public string BrojTelefona { get; set; }
        public int Lokal { get; set; }
        public long IdTipaTelefona { get; set; }
        public long IdOsobe { get; set; }
    
        public virtual Osoba Osoba { get; set; }
        public virtual TipTelefona TipTelefona { get; set; }
    }
}
